- hosts: localhost

  vars: 
    oracle_user: oracle
    oracle_group: oinstall
    oracle_base: /opt/oracle
    oracle_dirs:
      - '{{ oracle_base }}'
      - '{{ oracle_base }}/product'
      - '{{ oracle_base }}/oraInventory'
      - '[[ oracle_base }}/oradata'

  tasks: 
  - file:
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"
      path: "{{item}}"
      state: directory

    with_items:
      - "{{ oracle_dirs }}"
    become: yes
    become_user: root

