- hosts: localhost

  vars:
    oracle_user: oracle
    oracle_group: oinstall
    oracle_base: /opt/oracle
    install_unpacked: /opt/install/unpacked/
    home_oracle: /home/oracle
    oracle_version: 12.1.0.2
    oracle_hostname: "{{ ansible_fqdn }}"
    oracle_dba_group: dba
    oracle_install_group: oinstall
    oracle_home: '{{oracle_base}}/ptoduct/{{oracle_version}}/db1'
    oracle_inventory: /opt/oracle/oraInventory
    oracle_sid: ANSIBLE
    oracle_sys_password: 'ansible#1'
    oracle_system_password: '{{ oracle_sys_password }}'
    oracle_gdbname: orclansb

  tasks:
  - name: Copy DB responce file
    template:
      src: 'templates/dbca.rsp'
      dest: '{{ home_oracle }}/dbca.rsp'
      owner: '{{ oracle_user }}'
      group: '{{ oracle_group }}'
    become: yes
    become_user: root

  - name: Create database
    command: '{{ oracle_home }}/bin/dbca -silent -responseFile {{ home_oracle }}/dbca.rsp -datafileDestination {{ oracle_base }}/oradata'
    become: yes
    become_user: oracle

