- hosts: localhost

  vars: 
    oracle_user: oracle
    oracle_group: oinstall
    oracle_base: /opt/oracle
    install_unpacked: /opt/install/unpacked/
    home_oracle: /home/oracle
    oracle_version: 12.1.0.2
    oracle_hostname: "{{ ansible_fqdn }}"
    oracle_dba_group: dba
    oracle_install_group: oinstall
    oracle_home: '{{oracle_base}}/ptoduct/{{oracle_version}}/db1'
    oracle_inventory: /opt/oracle/oraInventory
    oracle_sid: ANSIBLE
    oracle_sys_password: ansible

  tasks: 
  - name: Copy responce file
    template:
      src: 'templates/db-{{ oracle_version }}.j2'
      dest: '{{ home_oracle }}/db-{{ oracle_version }}.rsp'
      owner: '{{ oracle_user }}'
      group: '{{ oracle_group }}'
    become: yes
    become_user: root
    
  - name: Install Oracle
    shell: > 
      {{ install_unpacked }}/database/runInstaller 
      -showProgress 
      -silent 
      -waitforcompletion 
      -ignoreSysPrereqs 
      -ignorePrereq 
      -responseFile {{ home_oracle }}/db-{{ oracle_version }}.rsp
      creates={{ oracle_home }}/bin
    become: yes
    become_user: oracle

