- hosts: localhost

  tasks:
  - name: Modify sysctl
    lineinfile:
     path: /etc/sysctl.conf
     state: present
     regexp: '^{{item.name}}={{item.value}}'
     line: "{{item.name}}={{item.value}}"
    with_items:
    - { name: fs.suid_dumpable, value: 1 }
    - { name: fs.aio-max-nr, value: 1048576 }
    - { name: fs.file-max, value: 6815744 }
    - { name: kernel.shmall, value: 2097152 }
    - { name: kernel.shmmax, value: 536870912 }
    - { name: kernel.shmmni, value: 4096 }
    - { name: kernel.sem, value: '"250 32000 100 128"' }
    - { name: net.ipv4.ip_local_port_range, value: '"9000 65500"' }
    - { name: net.core.rmem_default, value: 4194304 }
    - { name: net.core.rmem_max, value: 4194304 }
    - { name: net.core.wmem_default, value: 262144 }
    - { name: net.core.wmem_max, value: 1048586 }
    become: yes
    become_user: root

